### PR TITLE
Fixes #20: Version normalization adds unnecessary .0 

### LINKED ISSUE #20: Version normalization adds unnecessary .0
When I publish version 1.28.2, it's normalized an 1.28.2.0, which is wrong.

### PR DESCRIPTION
**Pull request by grasmash**
Fix #20

### CODE REVIEW

**Comment by danepowell** [comment]
@greg-1-anderson could you please review and merge this, and cut a new release if everything looks good?

We've been using it downstream for a while: https://github.com/acquia/cli/blob/ebb1cca2cefbc981a7bd7b9fc80b8ca52f71d408/composer.json#L111

Tests are failing in HEAD and I don't think the test failures here are caused by the PR.

**Comment by danepowell** [comment]
In main, running self-update will always download the latest release even if the current version _is_ the latest (i.e. no update is required), because Composer's normalized version format includes this trailing zero, which doesn't generally match semver.

I've confirmed this is the behavior today in Terminus. It's also the behavior in Acquia CLI if we remove this patch.

I'd argue this is a bug, but I could see how it might be a feature (if a user suspects their phar is corrupt and requests an update, they should get an update even if it's not strictly necessary).

Fixing this bug here could be disruptive, as evidenced by the failing tests. I think the safest solution is for Acquia CLI to just append a zero to its internal version and abandon this patch, unless Terminus also wants an upstream fix.

**Comment by greg-1-anderson** [comment]
I don't think that this would hurt Terminus, but Terminus always uses three-digit version numbers, so I don't think it is necessary.

**Comment by danepowell** [comment]
In hindsight, this PR was a valid issue, it just needed a little more work: #25

**Pull request closed without merging**
