### PR TITLE
Add Symfony 5 support

### PR DESCRIPTION
**Pull request by k0d3r1s**
Add Symfony 5 support

#SymfonyHackday

### CODE REVIEW

**Comment by lesichkovm** [comment]
When is this going to be merged?

**Comment by alsar** [comment]
@greg-1-anderson can this get merged?

**Comment by danepowell** [comment]
This looks to have been committed here and can be closed: https://github.com/consolidation/self-update/commit/dba6b2c0708f20fa3ba8008a2353b637578849b4

**Comment by k0d3r1s** [comment]
@greg-1-anderson so, instead of merging year old pr, you just went and commited same yourself? bit rude don't you think?

**Comment by greg-1-anderson** [comment]
@k0d3r1s There was no value to this PR, because there was no indication that any testing had been done, so I couldn't just merge it. By the time I circled back here as part of my own effort, I forgot it was here.

If you want to help maintainers and actually save them time, include tests, or at least document what work you did to manually test. Contribution is not all about participation trophies.

**Comment by k0d3r1s** [comment]
@greg-1-anderson i did test when i changed it, otherwise i wouldn't have submitted pr. and your project does not have contribution guidelines, so I couldn't have known what input you wanted for it, especially since pr was open for a year and you did not ask for any input

**Pull request closed without merging**
